name: Search Action
description: Search for a string in the repo
inputs:
  search-pattern:
    description: String pattern to search for
    required: true
  exclude-dir:
    description: Comma separated list of directories to exclude from the search
    default: .git
  fail-if-found:
    description: If enabled, fail if the pattern is found
    default: "true"
runs:
  using: "composite"
  steps:
    # Don't check out the repo here, and just use whichever repo(s) and files are currently in
    # the workspace.
    - name: Search for "${{ inputs.search-pattern }}"
      id: search
      run: |
        matching_files=$(grep -rnil --exclude-dir="${{ inputs.exclude-dir }}" "${{ inputs.search-string }}" . || true)
        echo "Found matching file(s):"
        echo $matching_files
        echo "matches=$matches" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Fail if pattern is found
      if: ${{ inputs.fail-if-found == 'true' }}
      run: |
        matches="${{ steps.search.outputs.matches }}"
        [[ -z $matches ]] || {
          >&2 echo "Pattern detected in the following files(s):"
          >&2 echo "$matches" | tr " " "\n"
          exit 1
        }
      shell: bash
