name: Search Action
description: Search for a string in the repo
inputs:
  search-pattern:
    description: String pattern to search for
    required: true
  exclude-dirs:
    description: Comma separated list of directories to exclude from the search
    default: .git
  fail-if-found:
    description: If enabled, fail if the pattern is found
    default: "true"
  search-path:
    description: Path to search for
    default: .
runs:
  using: "composite"
  steps:
    # Don't check out the repo here, and just use whichever repo(s) and files are currently in
    # the workspace.
    - name: Search for "${{ inputs.search-pattern }}"
      id: search
      run: |
        echo "Searching for files with the string: ${{ inputs.search-string }}"
        # Use grep to find files containing the specified string
        # Adjust the file patterns and search options as needed
        matching_files=$(grep -r -l "${{ inputs.search-string }}" . || true)

        # Check if any files were found
        if [ -n "$matching_files" ]; then
          echo "Files containing the string:"
          echo "$matching_files"
          exit 1
        else
          echo "No files found containing the string."
          exit 0
        fi
      shell: bash
