name: Autotests Workflow
on:
  # push:
  #   branches:
  #     - main

  workflow_dispatch:

jobs:
  autotests:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  notify-slack:
    runs-on: ubuntu-latest
    needs:
      - autotests
    steps:
      - run: exit 0

  upload-dynamo:
    runs-on: ubuntu-latest
    needs:
      - autotests
    steps:
      - run: exit 0

  update-linear:
    runs-on: ubuntu-latest
    needs:
      - autotests
    steps:
      - run: exit 0

  post-github-comment:
    runs-on: ubuntu-latest
    if: ${{ false }}
    needs:
      - autotests
    steps:
      - run: exit 0
