name: Create Release Patch

on:
  push:
    branches:
      - release/**


jobs:
  tag-release-version:
    if: startsWith(github.ref_name, 'release/')
    uses: ./.github/workflows/tag-release-version.yml

  print-release-version:
    needs:
      - tag-release-version
    runs-on: ubuntu-latest
    steps:
      - name: Release Version
        run: |
          echo "::notice::Tagged release version: ${{ needs.tag-release-version.outputs.release-version }}"

