name: Test Workflow
on:
  push:
    branches:
      - main
      - 'releases/**'

  workflow_dispatch:

jobs:
  init:
    permissions:
      contents: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@v1.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

  test1:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - run: exit 0
  test2:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - run: exit 0

  post-build:
    needs:
      - test1
      - test2
    uses: jnguyen75/github-actions-test/.github/workflows/notification.yml@main
    with:
      # Job is determined successful if none of the builds failed or were cancelled.
      job_status: ${{ (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) && 'success' || 'failed' }}
      # status_context: ${{ github.workflow }}
    secrets: inherit
  
  post-build-2:
    runs-on: ubuntu-latest
    needs:
      - test1
      - test2
    steps:
      - run: echo "Needs ${{ toJSON(needs) }}"
