name: Test Workflow
on:
  push:
    branches:
      - main
      - 'releases/**'

  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  test2:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - run: exit 0

  notify-failure:
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    needs:
      - test1
      - test2
    uses: jnguyen75/github-actions-test/.github/workflows/notify-failure-slack.yml@main
    secrets: inherit
