name: Test 2 Workflow
on:
  push:
    branches:
      - main
      - 'releases/**'

  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@v1.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

  test3:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - run: exit 0

  notify-failure:
    if: ${{ contains(needs.*.result, 'failure') }}
    needs:
      - test3
    uses: jnguyen75/github-actions-test/.github/workflows/notify-failure-slack.yml@main
    secrets: inherit
