name: Test 2 Workflow
on:
  push:
    branches:
      - main
      - 'releases/**'

  workflow_dispatch:

jobs:
  test3:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  notify-failure:
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    needs:
      - test3
    uses: jnguyen75/github-actions-test/.github/workflows/notify-failure-slack.yml@main
    secrets: inherit
