name: Test Workflow
on:
  push:
    branches:
      - main
      - 'releases/**'

  workflow_dispatch:

jobs:
  init:
    permissions:
      contents: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@v1.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

  test1:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - run: exit 1
  test2:
    runs-on: ubuntu-latest
    if: ${{ false }}
    needs: init
    steps:
      - run: exit 0

  notify-failure:
    if: ${{ contains(needs.*.result, 'failure') }}
    needs:
      - test1
      - test2
    uses: jnguyen75/github-actions-test/.github/workflows/notify-failure-slack.yml@main
    secrets: inherit
