name: Test 2 Workflow
on:
  push:
    branches:
      - main
      - 'releases/**'

  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@v1.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

  test1:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - run: exit 0

  post-build:
    if: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
    needs:
      - test1
    uses: jnguyen75/github-actions-test/.github/workflows/notify-slack-failure.yml@send-on-failure
    with:
      # Job is a failure if any builds failed or were cancelled.
      commit_status: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
      status_context: ${{ github.workflow }}
    secrets: inherit
