name: Test Workflow
on:
  push:
    branches:
      - main
      - 'releases/**'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        default: test

jobs:
  init:
    permissions:
      contents: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@v1.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: Test Workflow

  test1:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - run: exit 1
  test2:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - run: exit 1