name: Test Workflow
on:
  push:
    branches:
      - main
      - 'releases/**'

  workflow_dispatch:

jobs:
  test-search-string:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check for 'donotcommit'
        id: search-string
        uses: jnguyen75/github-actions-test/actions/search-pattern@main
        with:
          search-pattern: donotcommit
      - name: Check for 'donotcommit' (fail if found)
        id: fail-if-found
        continue-on-error: true
        uses: jnguyen75/github-actions-test/actions/search-pattern@main
        with:
          search-pattern: donotcommit
          fail-if-found: true
      - name: Check for 'do.*commit' pattern (fail if found)
        id: search-pattern
        continue-on-error: true
        uses: jnguyen75/github-actions-test/actions/search-pattern@main
        with:
          search-pattern: do.*commit
          fail-if-found: true
      - name: Check for 'stringnotfound'
        id: search-string-not-found
        continue-on-error: true
        uses: jnguyen75/github-actions-test/actions/search-pattern@main
        with:
          search-pattern: stringnotfound
          fail-if-found: true
          exclude-dir: .git,.github
      - name: Check Test Results
        if: always()
        run: |
          code=0
          if [[ "${{ steps.search-string.outcome }}" != "success" ]]; then
            echo "Failed: check-search-string didn't succeed as expected"
            code=1
          fi
          if [[ "${{ steps.fail-if-found.outcome }}" != "failure" ]]; then
            echo "Failed: check-fail-if-found didn't fail as expected"
            code=1
          fi
          if [[ "${{ steps.search-pattern.outcome }}" != "failure" ]]; then
            echo "Failed: Test check-search-pattern didn't fail as expected"
            code=1
          fi
          if [[ "${{ steps.search-string-not-found.outcome }}" != "success" ]]; then
            echo "Failed: search-string-not-found didn't succeed as expected"
            code=1
          fi

          exit $code


  # notify-failure:
  #   if: ${{ always() && contains(needs.*.result, 'failure') }}
  #   needs:
  #     - test1
  #     - test2
  #   uses: jnguyen75/github-actions-test/.github/workflows/notify-failure-slack.yml@main
  #   secrets: inherit
